name: Generate Search Index

on:
  push:
    paths:
      - 'src/files/bardicNames.json'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Generate search index
        run: node scripts/generate-search-index.js
        
      - name: Commit and push if changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add src/data/search-index.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update search index" && git push)